### ISSUE TITLE
Installing the Agent on a Linux Server

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/cloud-eye#25]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-eye/blob/main/umn/source/server_monitoring/installing_and_configuring_the_agent_on_a_linux_ecs_or_bms/installing_the_agent_on_a_linux_server.rst

according to the page, the following URL should be called to get the shell script:
https://telescope-eu-de.obs.eu-de.otctest.t-systems.com/scripts/agentInstall.sh 

However, I get the following error message:
--2023-05-30 13:56:39-- (try: 4) https://telescope-eu-de.obs.eu-de.otctest.t-systems.com/scripts/agentInstall.sh
Connecting to telescope-eu-de.obs.eu-de.otctest.t-systems.com (telescope-eu-de.obs.eu-de.otctest.t-systems.com)|80.158.0.81|:443... failed: Connection timed out.
Retrying.

**Comment by mrumpler2** [comment]
Next version of the CES documentation has to be updated with new URL

**Comment by mrumpler2** [comment]
Issue also addressed in gitea:

[[CES][UMN] Incorrect agent installation script for linux server](https://gitea.eco.tsi-dev.otc-service.com/docs/cloud-eye/issues/42)

**Comment by aziuzkotsystems** [comment]
The issue was resolved https://gitea.eco.tsi-dev.otc-service.com/docs/cloud-eye/issues/42
