### ISSUE TITLE
Reference name for GaussDB(for MySQL) and for GaussDB(for openGauss)  is same

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud-docs/cloud-eye#33]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-eye/blob/main/api-ref/source/appendix/services_interconnected_with_cloud_eye.rst

There are GuassDB (for MySQL)  and GaussDB (for openGauss) but for Reference linked for both has same name "GaussDB(for MySQL) metrics".   Links is correctly set, one to GaussDB(for MySQL) and another for GaussDB(for openGauss)  ,  it is just name of the reference.

![image](https://github.com/opentelekomcloud-docs/cloud-eye/assets/96316177/9f358012-0e62-4247-88d6-425265d5b6e2)

**Comment by aziuzkotsystems** [comment]
The issue was resolved 
![image](https://github.com/opentelekomcloud-docs/cloud-eye/assets/122808277/bf45f9f7-724a-4b14-896d-e79eb0f7157e)
