### ISSUE TITLE
Installing the Agent on a Linux Server

### ISSUE THREAD

**Issue by simfeiOTC** [opentelekomcloud-docs/cloud-eye#35]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-eye/blob/main/umn/source/server_monitoring/installing_and_configuring_the_agent_on_a_linux_ecs_or_bms/installing_the_agent_on_a_linux_server.rst

The Link  for installing the agent should be the same one but instead of otctest, it should be otc only as you can see in the screenshot.

![screen](https://github.com/opentelekomcloud-docs/cloud-eye/assets/155572270/adb76a7e-5095-46d6-8a19-779f147031c5)

**Comment by mrumpler3** [comment]
The problem will be fixed in the next UMN version (https://gitea.eco.tsi-dev.otc-service.com/docs/cloud-eye/pulls/61):
![image](https://github.com/user-attachments/assets/66add8b3-5d37-4f3e-ba73-28a2ab535fad)

**Comment by mrumpler3** [comment]
Issue fixed
![image](https://github.com/user-attachments/assets/7bbef82b-8745-46e6-9c5a-e50682a7481b)

**Comment by mrumpler3** [comment]
fixed
